import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsProvider from "@/providers/StyledComponentsProvider";
import "devextreme/dist/css/dx.light.css";
import { ReactNode } from "react";
import * as S from "./styles";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dx-viewport`}>
        <StyledComponentsProvider>
          <S.Layout>
            <Navbar />
            <S.RowContainer>
              <Sidebar />
              {children}
            </S.RowContainer>
          </S.Layout>
        </StyledComponentsProvider>
      </body>
    </html>
  );
}
